### ISSUE TITLE
Conn string in docs tutorial could be improved

### ISSUE THREAD

**Issue by chrisbroski** [yandex/pgmigrate#12]
Since you are instructing the user to explicitly create a group *foo* with password *foo*, you should include that in the connection string in `migrations.yml` file like so:

> conn:  host=localhost dbname=foodb user=foo password=foo

**Comment by secwall** [comment]
We could do this but storing connection string in `migrations.yml` is not recommended.
Because this file is stored in your VCS and have the same content on different environments.
On the other side connection string is often different on different envs.

**Comment by chrisbroski** [comment]
Yes that's true, but you are explicitly setting a password in the tutorial.md file:

> postgres=# CREATE ROLE foo WITH LOGIN PASSWORD 'foo';
> CREATE ROLE

So you should be consistent. Either don't set the password here, or include it in the tutorial config.

**Comment by secwall** [comment]
Actually I don't see any inconsistency with our approach.
It is really bad idea to pass password as part of command line arguments or config that is supposed to be added into VCS. In PostgreSQL [pgpass](https://www.postgresql.org/docs/current/static/libpq-pgpass.html) usage is a way to store passwords. But it seems to be out of scope for migration tool documentation.

**Comment by chrisbroski** [comment]
Then please mention it in the tutorial file. A tutorial should be a simple follow-the-numbers affair. In its current state, If you follow the instructions, it doesn't work.

**Comment by secwall** [comment]
Actually it seems to be unnecessary. We don't mention installing PostgreSQL, configuring it and so on. Secure password storage is also out of scope.
