### ISSUE TITLE
Параметр командной строки для отключения проверки на ascii

### ISSUE THREAD

**Issue by olegkudrin** [yandex/pgmigrate#17]
Возможно ли добавить параметр командной строки для отключения проверки на ascii? В моем случае есть большое количество кода на pl/pgsql с русским текстом, десятки и сотни файлов. Прописать в каждый файл специальный комментарий затруднительно.

**Comment by secwall** [comment]
Я не очень понимаю, в чём проблема добавления комментария в каждый файл? Это ведь можно сделать один раз достаточно простой комбинацией из `find` и `sed`.

**Comment by olegkudrin** [comment]
Проблема только в необходимости добавлять лишнее во всю сотню файлов, с которыми постоянно работаешь по предментой части. Подобно как в питоне 2 нужно было добавлять coding, не даром же в питоне 3 utf-8 по умолчанию. Потому альтернатива у меня использовать свой форк.

**Comment by olegkudrin** [comment]
Предлагаю закрыть эту заявку как мало значимую. В своем случае справился с проблемой генерацией временного скрипта перед запуском pgmigrate.
