### ISSUE TITLE
pgmigrate does not chooses a master when multiple hosts are passed in the connection string

### ISSUE THREAD

**Issue by svetlyak40wt** [yandex/pgmigrate#18]
When I start pgmigrate like this:

```
pgmigrate -l 1 -t 1000 -d /app/migrations -c "dbname=artdb host=host1.my.net,host2.my.net,host3.my.net port=5432 user=art" migrate
```

It would be great if `pgmigrate` will add `target_session_attrs=read-write` to the connection string if it is not already there.

**Comment by secwall** [comment]
We probably shouldn't modify connection string.
There are several problems with adding `target_session_attrs=read-write` to every conn string:
1) What if user just wants to get info about applied migrations and calls pgmigrate with a list of replicas? Pgmigrate will fail to connect.
2) What if user always set session param `-s "SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE"` in pgmigrate call and role has `default_transaction_read_only = on` setting? Pgmigrate will also fail to connect.

So we need to check if we are going to write anything or mess with session params in our call in case of several hosts in conn string. There are probably more problematic cases. I just came with 2 after about 5 minutes of thinking.
If caller put several hosts in conn string why not just add desired `target_session_attrs`?

**Comment by svetlyak40wt** [comment]
Added workaround into my own wrapper around pgmigrate.
