### ISSUE TITLE
Ошибка, база не существует

### ISSUE THREAD

**Issue by shizacat** [yandex/pgmigrate#20]
В версии 1.0.5 появилась ошибка

> psycopg2.OperationalError: FATAL:  database "test application_name=pgmigrate-266dd3f1-081e-4ef1-ae86-5124a32" does not exist

Может вы хотели  в (https://github.com/yandex/pgmigrate/blob/master/pgmigrate.py#L162) добавить: **?**
`conn = _create_raw_connection('{dsn}?application_name={conn_id}'.format(`

**Comment by secwall** [comment]
`test?application_name={conn_id}` не будет корректным `dsn` с точки зрения `psycopg2`.
В 790870c сделал более безопасную работу с dsn, теперь если передать там просто `test` без `dbname=test`, то `pgmigrate` будет ругаться.

**Comment by shizacat** [comment]
Все заработало )) Спасибо. Уже стою в очереди за следующим релизом ;)
