### ISSUE TITLE
info order problem

### ISSUE THREAD

**Issue by bahmatovich** [yandex/pgmigrate#3]
Some times info command shows versions in wrong order.

"32": {
        "description": "***",
        "transactional": true,
        "version": 32,
        "installed_on": "2017-03-29 18:58:34",
        "type": "auto",
        "installed_by": "***"
    },
 "12": {
        "description": "***",
        "transactional": true,
        "version": 12,
        "installed_on": "2017-03-02 21:23:48",
        "type": "manual",
        "installed_by": "***"
    },
 "13": {
        "description": "***",
        "transactional": true,
        "version": 13,
        "installed_on": "2017-03-02 21:24:17",
        "type": "auto",
        "installed_by": "***"
    },
....

**Comment by secwall** [comment]
It is expected behavior. There is no order in versions in info command. Why do you need them sorted?

**Comment by bahmatovich** [comment]
Then i run it in console, i expect that last line (last block) describes last migration version.
If there are many versions, then it is difficult to see the sequence.

**Comment by secwall** [comment]
Fixed by change in 77d7df4.
