### ISSUE TITLE
Safe concurrent migrations?

### ISSUE THREAD

**Issue by FRosner** [yandex/pgmigrate#36]
Consider the situation where we want to run the migrations as part of application startup. If we have multiple application containers running concurrently, is pgmigrate taking care of this internally, e.g. by locking, to make it safe to run concurrent migrations? Flyway does it, so I was wondering if it's also safe here.

**Comment by secwall** [comment]
No. Concurrent migrations are not safe in pgmigrate.

**Comment by FRosner** [comment]
Thanks! Do you think it would be possible to implement without code changes by utilizing advisory locks inside the `beforeAll` and `afterAll` callbacks?

**Comment by secwall** [comment]
You could try to take an [advisory lock](https://www.postgresql.org/docs/15/explicit-locking.html#ADVISORY-LOCKS) during [session setup](https://github.com/yandex/pgmigrate/blob/master/doc/tutorial.md#session-setup). But it will not work in all cases (e.g. nontransactional migrations).

**Comment by FRosner** [comment]
What would be the difference between locking as part of the session setup vs as part of the callback?

**Comment by secwall** [comment]
Basically, locking on session setup protects against multiple backends reading the schema version table and starting migrations in multiple independent sessions. With locking on beforeAll, the callback lock would only be taken when pgmigrate decides to start performing migrations. Unfortunately, only one backend will be successful. All others will fail after the lock is taken (with errors like "column already exists" and so on).

**Comment by FRosner** [comment]
> locking on session setup protects against multiple backends reading the schema version table and starting migrations in multiple independent sessions.

I see... so I can see how I can acquire the lock during session setup. How do I release it when I'm done?

**Comment by secwall** [comment]
When the pgmigrate connection is closed, the lock is automatically released.

**Comment by FRosner** [comment]
Thanks!
