### ISSUE TITLE
psycopg2 dependency should use psycopg2-binary instead

### ISSUE THREAD

**Issue by jblang** [yandex/pgmigrate#37]
When I install yandex-pgmigrate via pip, it tries to build psycopg2 from source, which breaks the virtualenv setup for anyone who doesn't have a proper C toolchain set up. psycopg2 is the source package, and you have to use psycopg2-binary if you want to use the pre-built binary.  I tried manually install psycopg2-binary first but pgmigrate insists on using the source package. I think this just needs to be changed in setup.py.  Also, any plans to upgrade to psycopg3? psycopg2 is terrible for more reasons than just this.

**Comment by secwall** [comment]
[psycopg2-binary readme](https://pypi.org/project/psycopg2-binary/) says:
```
The binary package is a practical choice for development and testing but in
production it is advised to use the package built from sources.
```
So we use the production-ready approach of depending on psycopg2 instead of psycopg2-binary.
There are no plans to upgrade to psycopg3 as it does not support python2 and pgmigrate is still supporting it.

**Comment by jblang** [comment]
"Advised" but without giving any reasons... oh well. Closing this anyway as we have switched to Alembic.
