### ISSUE TITLE
Environment-dedicated migrations

### ISSUE THREAD

**Issue by metheoryt** [yandex/pgmigrate#8]
Use case: you have production and development environments. 
Development db requires some test data to be inserted after certain migrations applied (like new table created) e.g., for (auto)testing purposes, whereas production environment definitely doesn't need this data.
How's it possible to handle this case?

**Comment by secwall** [comment]
You could add afterAll callback in your pgmigrate call.
Example:
```
#prod
pgmigrate -c <prod conn string> -t latest migrate

#test
pgmigrate -c <test conn string> -a afterAll:testdata/mytest.sql -t latest migrate
```

**Comment by metheoryt** [comment]
That's a suitable solution, but:

Let's assume we have an empty staging database, and we've made initial migration V1 on it. We launch some application, which filling our database V1 with user data.

After some time, our migration V2 is ready to be deployed, and it brings many changes into our current schema. It drops some columns, adds some columns with default values, combines some columns into one, and so on. Of course, it makes `UPDATE` statements on existing data too.

What are cons of `afterAll` callback with this case?
1. We need to manually change test data sets with each such migration added.
2. We cannot do migration on e.g. V3, if we already have V4 (and test data is for V4 now). Assuming db code is under VCS, for this purpose we need to checkout commit, which contains V3 as last added migration. 
Actually, we can handle this, if we'll create separate test-data-file for each such migration, link it with desired migration through filename by migration id or similar, like `testdata/V004__data.sql` for `migrations/V004__many_changes.sql`, and make some script-workaround. But it is still workaround.
3. We cannot prove that our test data (and so user data will) migrated as desired as we inserting it after all migrations are done.

**Comment by secwall** [comment]
This is correct. But in order to handle all such issues pgmigrate should become a much more complex solution. And we are trying to limit our scope to simple migration tool for PostgreSQL databases.

**Comment by p0123n** [comment]
@metheoryt Hey, you can check my fork, seems like it something that you looking for
https://github.com/p0123n/pgmigrate

**Comment by man-brain** [comment]
> 1. We need to manually change test data sets with each such migration added.

Yep, and how do you want to handle it in separate migrations for particular environment? Maybe I'm missing something but it seems that you would still need to change them too.

> 2. We cannot do migration on e.g. V3, if we already have V4 (and test data is for V4 now). Assuming db code is under VCS, for this purpose we need to checkout commit, which contains V3 as last added migration.

Yes. And you probably don't want to have migrations not under VCS control. Suppose, that you also have schema `code` with stored functions and you deploy it every time from scratch (`DROP SCHEMA IF EXISTS code CASCADE; CREATE SCHEMA code; ...`). If code for version 4 doesn't work with schema version 3 and you want to deploy some DB to version 3 with code that works for version 3, the only way to do it is to checkout needed commit from VCS. This is pretty frequent use case. And we definitely don't want to implement VCS logic inside pgmigrate.

> 3. We cannot prove that our test data (and so user data will) migrated as desired as we inserting it after all migrations are done.

I don't think I have understood you correct. Could you give an example of a problem?

Could you provide a better idea of the way to handle your problem?

**Comment by metheoryt** [comment]
> If code for version 4 doesn't work with schema version 3 and you want to deploy some DB to version 3 with code that works for version 3, the only way to do it is to checkout needed commit from VCS.

@dev1ant, I mean case, in which you have 100 migrations and test data V100, and then you trying to migrate not to latest version, for example 42. While in afterAll callback, test data V100 rolls upon wrong migration version.

> I don't think I have understood you correct. Could you give an example of a problem?

Imagine you have migration V1, which adds JSON field `my_table.config`. It had simple structure `{foo: string, bar: string}` and test data V1 looks like `INSERT INTO my_table VALUES ('{"foo": "baz", "bar": "ges"}'), ('{"foo": null, "bar": ""}')`.

But then you had to scatter both foo and bar on columns. You're doing this in migration V2, 
and changing test data to `INSERT INTO my_table(foo, bar) VALUES ('baz', 'ges'), (NULL, '')`.
But if you changing your test datasets manually, your test data after migration V2 can differ from your test dataset V2, and it shouldn't.

> Could you provide a better idea of the way to handle your problem?

I think of it as of a production database workflow. Creating schema, filling with static data, filling with user data, migrating, filling with user data, migrating and so on. 
It could looks like this:
```
V1000__Initial_migration.sql
V1010__Static_data.sql
V1011__test__example_data.sql
V1020__New_table.sql
V1021__test__example_data_for_new_table.sql
...
```
where `test` followed by two underscores - environment name. They'll be executed if `--add-env=test` parameter will be passed to pgmigrate, and they'll preserve the order of execution.

Realization can differ, but I think you've got the basic idea.

**Comment by metheoryt** [comment]
@p0123n custom config name is a cool improvement, I just missed it today, already watched your fork :+1:

**Comment by man-brain** [comment]
>  I mean case, in which you have 100 migrations and test data V100, and then you trying to migrate not to latest version, for example 42. While in afterAll callback, test data V100 rolls upon wrong migration version.

Aren't your migrations under VCS? Why don't you want to solve the problem with a tool that is designed to solve your problem?

>Imagine you have migration V1, which adds JSON field my_table.config. It had simple structure {foo: string, bar: string} and test data V1 looks like INSERT INTO my_table VALUES ('{"foo": "baz", "bar": "ges"}'), ('{"foo": null, "bar": ""}').
But then you had to scatter both foo and bar on columns. You're doing this in migration V2,
and changing test data to INSERT INTO my_table(foo, bar) VALUES ('baz', 'ges'), (NULL, '').

Would you understand well enough, how does your test data look after another hundred migrations?
If you insert data for testing purposes, why don't you do it in your tests logic? I still don't think that tool for migrations should solve problems of VCS tool or testing tool.

And I don't actually like the idea of running the same migrations in different envs and getting different results. The purpose of pgmigrate is to preserve the same schema.
